 #Version 0.0.1
 FROM ubuntu:18.04

 LABEL maintainter="nebojshatodorovivik@yahoo.com"

 RUN apt-get update; apt-get install -y nginx
 RUN echo 'Hi I am in the containter now....NECOOO' > /var/www/html/index.html
 
 EXPOSE 80
